# -*- coding: utf-8 -*-
"""lego_project_solution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V4CuWbjINeKMl8EtxbdxtAKjkL3WsLlv

## 1. Introduction
<p>Everyone loves Lego (unless you ever stepped on one). Did you know by the way that "Lego" was derived from the Danish phrase leg godt, which means "play well"? Unless you speak Danish, probably not. </p>
<p>In this project, we will analyze a fascinating dataset on every single lego block that has ever been built!</p>
<p><img src="https://s3.amazonaws.com/assets.datacamp.com/production/project_10/datasets/lego-bricks.jpeg" alt="lego"></p>
"""

# Nothing to do here

"""## 2. Reading Data
<p>A comprehensive database of lego blocks is provided by <a href="https://rebrickable.com/downloads/">Rebrickable</a>. The data is available as csv files and the schema is shown below.</p>
<p><img src="https://s3.amazonaws.com/assets.datacamp.com/production/project_10/datasets/downloads_schema.png" alt="schema"></p>
<p>Let us start by reading in the colors data to get a sense of the diversity of lego sets!</p>
"""

# Import modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
# Read colors data
colors = pd.read_csv('colors.csv')
sets = pd.read_csv('sets.csv')
# Print the first few rows
display(colors.head(10))
display(sets.head(10))

"""## 3. Exploring Colors
<p>Now that we have read the <code>colors</code> data, we can start exploring it! Let us start by understanding the number of colors available.</p>
"""

# How many distinct colors are available?
num_colors = colors.shape[0]

n_colors = colors['name'].nunique()
print('the number of distinct color is {}'.format(n_colors))

# string manipulation.
colors.head()
colors['name'] = colors['name'].apply(lambda x : x.lower())

# removing space between words in name column due to easier manipulation. 
colors['name'] = [i.replace(' ' , '_')  for i in colors['name']]
colors.head()

plt.figure(figsize=(20,10))
sns.countplot(colors['name'] , edgecolor = 'k' , palette='Set1')
plt.xticks(rotation = 90)

# Just for sample.
# Don't do this at home :)). use list comprehensions and if statement.
colors['name'] = colors['name'].replace(['light_green' , 'trans-neon_green' , 'trans-green' , 'dark_green' , 'olive_green' , 'chrome_green' ,'medium_green'] , 'green')
colors['name'] = colors['name'].replace(['light_gray' , 'light_bluish_gray' , 'pearl_very_light_gray' , 'very_light_gray' , 'pearl_light_gray' , 'very_light_bluish_gray'] , 'grey')
colors['name'] = colors['name'].replace(['light_blue' , 'trans-dark_blue' , 'trans-light_blue' , 'trans-very_lt_blue' , 'royal_blue' , 'trans-medium_blue' , 'bright_light_blue' , 'dark_blue' , 'sand_blue' , 'glitter_trans-light_blue' , 'trans_light_royal_blue'] , 'blue')
colors['name'].value_counts()

plt.figure(figsize=(20,10))
sns.countplot(colors['name'] , edgecolor = 'k')
plt.xticks(rotation = 90)

colors['name'].unique()

colors.head()

"""## 4. Transparent Colors in Lego Sets
<p>The <code>colors</code> data has a column named <code>is_trans</code> that indicates whether a color is transparent or not. It would be interesting to explore the distribution of transparent vs. non-transparent colors.</p>
"""

# colors_summary: Distribution of colors based on transparency
colors_summary = colors.groupby(colors['is_trans']).count()
colors_summary

plt.style.use('fivethirtyeight')
sns.set_palette('Set1')
sns.barplot(x = colors_summary.index  , y = 'name' , data = colors_summary)
plt.title('Distribution of colors based on transparency')

"""## 5. Explore Lego Sets
<p>Another interesting dataset available in this database is the <code>sets</code> data. It contains a comprehensive list of sets over the years and the number of parts that each of these sets contained. </p>
<p><img src="https://imgur.com/1k4PoXs.png" alt="sets_data"></p>
<p>Let us use this data to explore how the average number of parts in Lego sets has varied over the years.</p>
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
# Read sets data as `sets`
sets = pd.read_csv('sets.csv')

print(sets.head())

# Create a summary of average number of parts by year: `parts_by_year`
parts_by_year = sets[['year', 'num_parts']].groupby('year', as_index=False).mean()
# Plot trends in average number of parts by year
parts_by_year.plot(x = 'year', y = 'num_parts' , color = 'darkblue')
plt.annotate(xy=(2009,300) , xytext = (1999,300) ,s = 'most successful year', arrowprops=dict(arrowstyle="->",
                            connectionstyle="angle3,angleA=0,angleB=-90" , facecolor ='green'))
parts_by_year.head()

"""## 6. Lego Themes Over Years
<p>Lego blocks ship under multiple <a href="https://shop.lego.com/en-US/Themes">themes</a>. Let us try to get a sense of how the number of themes shipped has varied over the years.</p>
"""

# themes_by_year: Number of themes shipped by year
themes_by_year = sets[['year', 'theme_id']].groupby('year', as_index=False).count()
themes_by_year.head()

"""## 7. Wrapping It All Up!
<p>Lego blocks offer an unlimited amount of fun across ages. We explored some interesting trends around colors, parts, and themes. </p>
"""

# good luck !